/*

 BKG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 27

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bkgTilesBank 0

/* Super Gameboy palette 0 */
#define bkgTilesSGBPal0c0 6076
#define bkgTilesSGBPal0c1 8935
#define bkgTilesSGBPal0c2 6596
#define bkgTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bkgTilesSGBPal1c0 6076
#define bkgTilesSGBPal1c1 8935
#define bkgTilesSGBPal1c2 6596
#define bkgTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bkgTilesSGBPal2c0 6076
#define bkgTilesSGBPal2c1 8935
#define bkgTilesSGBPal2c2 6596
#define bkgTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bkgTilesSGBPal3c0 6076
#define bkgTilesSGBPal3c1 8935
#define bkgTilesSGBPal3c2 6596
#define bkgTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bkgTilesCGBPal0c0 32767
#define bkgTilesCGBPal0c1 26425
#define bkgTilesCGBPal0c2 19026
#define bkgTilesCGBPal0c3 20

/* Gameboy Color palette 1 */
#define bkgTilesCGBPal1c0 29670
#define bkgTilesCGBPal1c1 5
#define bkgTilesCGBPal1c2 2132
#define bkgTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define bkgTilesCGBPal2c0 32767
#define bkgTilesCGBPal2c1 6141
#define bkgTilesCGBPal2c2 19026
#define bkgTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define bkgTilesCGBPal3c0 13665
#define bkgTilesCGBPal3c1 31
#define bkgTilesCGBPal3c2 19026
#define bkgTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define bkgTilesCGBPal4c0 6076
#define bkgTilesCGBPal4c1 32067
#define bkgTilesCGBPal4c2 19026
#define bkgTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define bkgTilesCGBPal5c0 757
#define bkgTilesCGBPal5c1 8935
#define bkgTilesCGBPal5c2 19026
#define bkgTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bkgTilesCGBPal6c0 6076
#define bkgTilesCGBPal6c1 125
#define bkgTilesCGBPal6c2 6596
#define bkgTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define bkgTilesCGBPal7c0 6076
#define bkgTilesCGBPal7c1 17410
#define bkgTilesCGBPal7c2 19026
#define bkgTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char bkgTilesCGB[];
/* Start of tile array. */
extern unsigned char bkgTiles[];

/* End of BKG.H */
