/*

 BKGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : bkg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkgMapWidth 32
#define bkgMapHeight 32
#define bkgMapBank 0

#define bkgMap bkgMapPLN0
extern unsigned char bkgMapPLN0[];
extern unsigned char bkgMapPLN1[];

/* End of BKGMAP.H */
