/*

 CURSORES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define cursoreDataBank 0

/* Super Gameboy palette 0 */
#define cursoreDataSGBPal0c0 6076
#define cursoreDataSGBPal0c1 8935
#define cursoreDataSGBPal0c2 6596
#define cursoreDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define cursoreDataSGBPal1c0 6076
#define cursoreDataSGBPal1c1 8935
#define cursoreDataSGBPal1c2 6596
#define cursoreDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define cursoreDataSGBPal2c0 6076
#define cursoreDataSGBPal2c1 8935
#define cursoreDataSGBPal2c2 6596
#define cursoreDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define cursoreDataSGBPal3c0 6076
#define cursoreDataSGBPal3c1 8935
#define cursoreDataSGBPal3c2 6596
#define cursoreDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define cursoreDataCGBPal0c0 6076
#define cursoreDataCGBPal0c1 8935
#define cursoreDataCGBPal0c2 32767
#define cursoreDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define cursoreDataCGBPal1c0 6076
#define cursoreDataCGBPal1c1 8935
#define cursoreDataCGBPal1c2 6596
#define cursoreDataCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define cursoreDataCGBPal2c0 6076
#define cursoreDataCGBPal2c1 8935
#define cursoreDataCGBPal2c2 6596
#define cursoreDataCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define cursoreDataCGBPal3c0 6076
#define cursoreDataCGBPal3c1 8935
#define cursoreDataCGBPal3c2 6596
#define cursoreDataCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define cursoreDataCGBPal4c0 6076
#define cursoreDataCGBPal4c1 8935
#define cursoreDataCGBPal4c2 6596
#define cursoreDataCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define cursoreDataCGBPal5c0 6076
#define cursoreDataCGBPal5c1 8935
#define cursoreDataCGBPal5c2 6596
#define cursoreDataCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define cursoreDataCGBPal6c0 6076
#define cursoreDataCGBPal6c1 8935
#define cursoreDataCGBPal6c2 6596
#define cursoreDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define cursoreDataCGBPal7c0 6076
#define cursoreDataCGBPal7c1 8935
#define cursoreDataCGBPal7c2 6596
#define cursoreDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char cursoreDataCGB[];
/* Start of tile array. */
extern unsigned char cursoreData[];

/* End of CURSORES.H */
