/*

 CURSORES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char cursoreDataCGB[] =
{
  0x00
};
/* Start of tile array. */
unsigned char cursoreData[] =
{
  0x00,0x00,0x18,0x18,0x14,0x1C,0x12,0x1E,
  0x11,0x1F,0x13,0x1F,0x1D,0x1F,0x06,0x06
};

/* End of CURSORES.C */
