/*

 MINESWIPPER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 18
   Tile set      : C:\gbdk\MyProjects\Mineswipper\data\bkg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mineswipperLabelWidth 21
#define mineswipperLabelHeight 18
#define mineswipperLabelBank 0

#define mineswipperLabel mineswipperLabelPLN0
extern unsigned char mineswipperLabelPLN0[];
extern unsigned char mineswipperLabelPLN1[];

/* End of MINESWIPPER.H */
