/*

 TITLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\MyProjects\Mineswipper\data\bkg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define titleMapWidth 20
#define titleMapHeight 18
#define titleMapBank 0

#define titleMap titleMapPLN0
extern unsigned char titleMapPLN0[];
extern unsigned char titleMapPLN1[];

/* End of TITLEMAP.H */
