/*

 WINDOW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define windowBank 0

/* Super Gameboy palette 0 */
#define windowSGBPal0c0 6076
#define windowSGBPal0c1 8935
#define windowSGBPal0c2 6596
#define windowSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define windowSGBPal1c0 6076
#define windowSGBPal1c1 8935
#define windowSGBPal1c2 6596
#define windowSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define windowSGBPal2c0 6076
#define windowSGBPal2c1 8935
#define windowSGBPal2c2 6596
#define windowSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define windowSGBPal3c0 6076
#define windowSGBPal3c1 8935
#define windowSGBPal3c2 6596
#define windowSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define windowCGBPal0c0 6076
#define windowCGBPal0c1 1022
#define windowCGBPal0c2 31694
#define windowCGBPal0c3 0

/* Gameboy Color palette 1 */
#define windowCGBPal1c0 6076
#define windowCGBPal1c1 8935
#define windowCGBPal1c2 6596
#define windowCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define windowCGBPal2c0 6076
#define windowCGBPal2c1 8935
#define windowCGBPal2c2 6596
#define windowCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define windowCGBPal3c0 6076
#define windowCGBPal3c1 8935
#define windowCGBPal3c2 6596
#define windowCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define windowCGBPal4c0 6076
#define windowCGBPal4c1 8935
#define windowCGBPal4c2 6596
#define windowCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define windowCGBPal5c0 6076
#define windowCGBPal5c1 8935
#define windowCGBPal5c2 6596
#define windowCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define windowCGBPal6c0 6076
#define windowCGBPal6c1 8935
#define windowCGBPal6c2 6596
#define windowCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define windowCGBPal7c0 6076
#define windowCGBPal7c1 8935
#define windowCGBPal7c2 6596
#define windowCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char windowCGB[];
/* Start of tile array. */
extern unsigned char window[];

/* End of WINDOW.H */
